/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.emindsoft.pkdbus.xml -p pkdbusInterface
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef PKDBUSINTERFACE_H
#define PKDBUSINTERFACE_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.emindsoft.pkdbus.registry
 */
class ComEmindsoftPkdbusRegistryInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.emindsoft.pkdbus.registry"; }

public:
    ComEmindsoftPkdbusRegistryInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~ComEmindsoftPkdbusRegistryInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> installPackage(const QString &packageName)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(packageName);
        return asyncCallWithArgumentList(QStringLiteral("installPackage"), argumentList);
    }

    inline QDBusPendingReply<> openApp(const QString &openAppName)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(openAppName);
        return asyncCallWithArgumentList(QStringLiteral("openApp"), argumentList);
    }

    inline QDBusPendingReply<> removePackage(const QString &pacId)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(pacId);
        return asyncCallWithArgumentList(QStringLiteral("removePackage"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void helloDbus(bool in0);
    void isInstallSuccess(bool in0);
    void isPacRmvSuccess(bool in0);
};

namespace com {
  namespace emindsoft {
    namespace pkdbus {
      typedef ::ComEmindsoftPkdbusRegistryInterface registry;
    }
  }
}
#endif
