/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.emindsoft.pkdbus.xml -a pkdbusAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef PKDBUSADAPTOR_H
#define PKDBUSADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.emindsoft.pkdbus.registry
 */
class RegistryAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.emindsoft.pkdbus.registry")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.emindsoft.pkdbus.registry\">\n"
"    <signal name=\"isInstallSuccess\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </signal>\n"
"    <method name=\"installPackage\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"packageName\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    RegistryAdaptor(QObject *parent);
    virtual ~RegistryAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void installPackage(const QString &packageName);
Q_SIGNALS: // SIGNALS
    void isInstallSuccess(bool in0);
};

#endif
